from typing import Callable, Iterable


def clear(): ...
def align() -> int: ...
def align(face: int) -> int: ...
def invert() -> bool: ...
def invert(invert: bool) -> bool: ...
def callback(self, function: Callable[[int], None]) -> None: ...
def pixel(x: int, y: int) -> int: ...
def pixel(x: int, y: int, brightness: int) -> None: ...


def show(image: Iterable, delay=400, level=9,
         clear=False, wait=True, loop=False, fade=0) -> None: ...
