from typing import Callable, Tuple


def accelerometer(filtered=False) -> Tuple[int, int, int]: ...
def gyroscope(filtered=False) -> Tuple[int, int, int]: ...
def align_to_model(top: int, front: int) -> None: ...
def align_to_model(nsamples: int, callback: Callable[[int], None]) -> None: ...


def align_to_model(top: int, front: int, nsamples: int,
                   callback: Callable[[int], None]) -> None: ...


def yaw_pitch_roll() -> Tuple[int, int, int]: ...
def yaw_pitch_roll(yaw_preset: int) -> None: ...
def yaw_pitch_roll(yaw_correction: float) -> None: ...
def orientation() -> int: ...
def orientation(callback: Callable[[int], None]) -> int: ...
def gesture() -> int: ...
def gesture(callback: Callable[[int], None]) -> int: ...


TAPPED = 0
DOUBLETAPPED = 1
SHAKE = 2
FREEFALL = 3
